networks:
  dev:

services:
  nginx:
    ports:
      - "2000:80"
    build:
      dockerfile: ./frontend/Dockerfile
      context: ./

    depends_on:
      - backend
    networks:
      - dev


  backend:
    build:
      context: ./backend
    networks:
      - dev
